### ISSUE TITLE
Usage in ReadMe? 

### ISSUE THREAD

**Issue by thejones** [trailsjs/trailpack-router#16]
The usage references 
```
// config/trailpack.js

```
Was this file renamed to main.js?

**Comment by jaumard** [comment]
You're right :) now it's `main.js` need to update the Readme

**Comment by tjwebb** [comment]
I just noticed this typo yesterday as well. The trailpack archetype needs to be fixed: https://github.com/trailsjs/trailpack/blob/master/archetype/README.md#configure
