### ISSUE TITLE
Name of create policy is not consistant

### ISSUE THREAD

**Issue by KevinNTH** [trailsjs/trailpack-router#55]
Hi, 

When I create a Policy with `yo` : `yo trails:policy Auth` or `yo trails:policy AuthPolicy`, it's create me a file named `api/policies/Auth.js` with `AuthPolicy` class. In `api/policies/index.js`, I have `exports.Auth = require('./Auth')`.

So to use my policy : 
```js
// config/policies.js
module.exports = {
  ExampleController: {
    test: [ 'Auth.test' ] // Should be AuthPolicy.test
  }
}
```

But in the example (readme.md) there is :
```js
// config/policies.js
module.exports = {
  ExampleController: {
    test: [ 'ExamplePolicy.test' ]
  }
}
```

I find this is not consistent regarding to the `controllers` and `services` system which add `Controller` and `Service` prefix to the new generated controller or service. So when I generate a policy, I should have `AuthPolicy.js` instead of `Auth.js` isn't it ?

**The same note applies to `models` too**.

**Comment by konstantinzolotarev** [comment]
Bug related to trailsjs/generator-trails

**Comment by KevinNTH** [comment]
Ok, thanks. I am going to open it on this repository, and close this one :)

**Comment by konstantinzolotarev** [comment]
@KevinNTH Thank you very much !
