### ISSUE TITLE
Validation errors should return 400 (Bad Request) not 500 (server error)

### ISSUE THREAD

**Issue by scott-wyatt** [trailsjs/trailpack-router#61]
When validating routes in the route array, Joi validations return a 500 instead of a 400.

**Comment by jaumard** [comment]
Can you give some example ? I don't think this is related to trailpack-router, it's more trailpack-express/hapi depending on the one you use

**Comment by scott-wyatt** [comment]
Yeah, I was just finding this is more related to trailpack-express, I know where it is, I'll do a PR as soon as I can.
